puts "Deleting old data..."

User.destroy_all
Room.destroy_all
Booking.destroy_all

puts "suck seed"
r1 = Room.create(name:"OCEAN-VIEW ROOM",r_type:"Standard",price:399,capacity:3,pets:true, breakfast:false, description:"Relax into traditional Bahamian luxury – steps from the beach – in these spacious guest rooms featuring mahogany furnishings, hardwood floors and colourful tropical flourishes. Louvered doors open to a private terrace or balcony with direct ocean views.", image:"https://www.fourseasons.com/alt/img-opt/~70/publish/content/dam/fourseasons/images/web/BOC/BOC_164_aspect16x9.jpg")
r2 = Room.create(name:"GARDEN-VIEW ROOM",r_type:"Standard",price:399,capacity:2,pets:true, breakfast:false, description:"Inspiring a state of tropical bliss, these bright, spacious guest rooms welcome you with their vibrant Bahamian personality. Sliding glass doors lead outside to a private terrace or balcony overlooking lush greenery and exotic blooms.", image:"https://www.fourseasons.com/alt/img-opt/~70/publish/content/dam/fourseasons/images/web/BOC/BOC_162_aspect16x9.jpg")
r3 = Room.create(name:"OCEAN-VIEW ONE-BEDROOM SUITE",r_type:"Suite",price:699,capacity:2,pets:false, breakfast:true, description:"These one-bedroom suites are perfect as a romantic hideaway or a family home base. Separate from the king bedroom, the living room – with a queen sofabed and powder room – features sliding glass doors that open to the terrace or balcony with Atlantic views.", image:"https://www.fourseasons.com/alt/img-opt/~70/publish/content/dam/fourseasons/images/web/BOC/BOC_165_aspect16x9.jpg")
r4 = Room.create(name:"LUXURY OCEANFRONT SUITE",r_type:"Suite",price:599,capacity:2,pets:false, breakfast:true, description:"Steps from the beach, these one-bedroom suites capture the island spirit in a traditionally furnished living and dining area and a separate bedroom. Both open to the private terrace or balcony, furnished for outdoor dining or lounging.", image:"https://www.fourseasons.com/alt/img-opt/~70/publish/content/dam/fourseasons/images/web/BOC/BOC_163_aspect16x9.jpg")
r5 = Room.create(name:"LUXURY OCEANFRONT ROOM",r_type:"Standard",price:499,capacity:2,pets:true, breakfast:true, description:"Relax into traditional Bahamian luxury – steps from the beach – in these spacious guest rooms featuring mahogany furnishings, hardwood floors and colourful tropical flourishes. Louvered doors open to a private terrace or balcony with direct ocean views.", image:"https://www.fourseasons.com/alt/img-opt/~70/publish/content/dam/fourseasons/images/web/BOC/BOC_166_aspect16x9.jpg")
r6 = Room.create(name:"TWO-BEDROOM PLUNGE POOL VILLA",r_type:"Villa",price:999,capacity:2,pets:true, breakfast:true, description:"Nestled within tropical foliage, our newly renovated plunge pool villas are made for a private friends or family retreat. The living and dining area is enhanced by two bedrooms, each with its own bathroom. Bright and airy in design and spaciously appointed, French doors open to an enclosed courtyard with a plunge pool.", image:"https://www.fourseasons.com/alt/img-opt/~70..0,0000-56,6204-3000,0000-1687,5000/publish/content/dam/fourseasons/images/web/BOC/BOC_651_original.jpg")
r7 = Room.create(name:"THREE-BEDROOM BEACHFRONT VILLA RESIDENCE",r_type:"Villa",price:1399,capacity:6,pets:true, breakfast:true, description:"In a secluded beachfront setting with its own private infinity pool, this grand villa features vaulted ceilings, rich woods and polished marble floors throughout its opulent living and dining areas, full kitchen and three bedrooms, all tended by a 24-hour service team.", image:"https://www.fourseasons.com/alt/img-opt/~70..0,0000-130,2500-3000,0000-1687,5000/publish/content/dam/fourseasons/images/web/BOC/BOC_658_original.jpg")
r8 = Room.create(name:"FOUR-BEDROOM BEACHFRONT VILLA RESIDENCE",r_type:"Villa",price:1699,capacity:8,pets:true, breakfast:true, description:"Designed for entertaining, our most lavish beachfront hideaway features expansive living and dining areas, a full kitchen, outdoor lounges and a private infinity pool. With three bedrooms in the main villa, the fourth bedroom is a romantic pavilion tucked away in the garden for a little extra privacy.", image:"https://www.fourseasons.com/alt/img-opt/~70..0,0000-183,6184-3000,0000-1687,5000/publish/content/dam/fourseasons/images/web/BOC/BOC_659_original.jpg")
